### ISSUE TITLE
Dry/Wet

### ISSUE THREAD

**Issue by vvvar** [vvvar/PeakEater#10]

**Comment by yupyup-cmyk** [comment]
For this you would need to implement linear phase oversampling, no? Unless there's a way to do it with minimum phase

**Comment by vvvar** [comment]
Hm, then(if i get you right), one of the options could be to mix "dry" and "wet" directly while "clipping" stage, since current flow is kinda like this:
Input Gain -> Oversampler -> Pre-Filter -> Clipper -> Post-Filter -> Output Gain

**Comment by yonderehco1197** [comment]
> Hm, then(if i get you right), one of the options could be to mix "dry" and "wet" directly while "clipping" stage, since current flow is kinda like this: Input Gain -> Oversample(Up) -> Pre-Filter -> Clipper -> Post-Filter -> Oversample(Down) -> Output Gain

Using the parameter in oversampling modes turns the clipper into a comb filter. Still works correctly in default mode

**Comment by yonderehco1197** [comment]
Using the dry/wet parameter in oversampling modes turns the clipper into a comb filter. Still works correctly in default mode. 

Perhaps a separate issue should have been created for the next request. I apologise if that is the case. The gist is in the attached image, but I could be wrong and you meant dry/wet as the "last output" of the plugin.
![screenshot-mac](https://github.com/vvvar/PeakEater/assets/127718490/eb6a51b4-1b2f-4306-95b0-7e45c44df762)

**Comment by vvvar** [comment]
Hello @yonderehco1197. Thanks for the feedback and sorry for the long delay. Fixed both problems in the [v0.8.2](https://github.com/vvvar/PeakEater/releases/tag/v0.8.2).

**Comment by yonderehco1197** [comment]
Tested in all possible combinations of dry/wet and oversampling. It works without any problems.
Thank you!
