### ISSUE TITLE
Installer doesn't install any vst3

### ISSUE THREAD

**Issue by viceverser** [vvvar/PeakEater#2]
I ran the installer and could not find the vst3 in the designated common files folder, Win10 

Found an uninstall instance in 'Apps and Features' but couldn't find the plugin.

**Comment by vvvar** [comment]
Hi, thanks for heads-up!

Could you please check following locations?
`C:\Program Files\Common Files\Steinberg\VST3`
or
`C:\Program Files (x86)\Common Files\Steinberg\VST3`

By default, it should be installed to one of these locations.

**Comment by viceverser** [comment]
Shure can... i don't have Steinberg in either of the Common Files folders before install, after install it appears, but it is the ONLY plugin in all my vst3 plugins to add a NEW VST3 folder within a Steinberg folder, this seems to be an OLD folder structure used for vst2 but no longer naturally applies to VST3... Everything else is Common Files/VST3/etc... So 1. I couldn't find it with all the other Common Files VST3's and 2. Apps that are standard to propper VST3 folders scan for the actual VST3 folder so don't pick up your VST3 file. Is there a reason you have decidded to not use correct VST3 folder?

**Comment by vvvar** [comment]
Ah ok i see now, yes, i think i've just used a [path from the tutorial](https://docs.juce.com/master/tutorial_app_plugin_packaging.html#tutorial_app_plugin_packaging_installers_windows) but you're right, having "Steinberg" directory is a VST2-type of path and [for VST3](https://helpcenter.steinberg.de/hc/en-us/articles/115000177084-VST-plug-in-locations-on-Windows) default path is different.

Added to the [roadmap](https://github.com/vvvar/PeakEater/projects/2), will fix that in the nearest release.

**Comment by viceverser** [comment]
Awesome... Do you have a zip of the vst3 on it's own? Then I could try now without broken uninstaller. I prefer my Plugins clean like this anyway. :)

**Comment by vvvar** [comment]
Sure, updated the [Release page](https://github.com/vvvar/PeakEater/releases/tag/v0.2.1-beta) with the vst3 file. Let me know in case of issues with it. Thx!

**Comment by vvvar** [comment]
Published release [v.0.2.2-beta](https://github.com/vvvar/PeakEater/releases/tag/v0.2.2-beta) that should fix this issue(and also VST3 file).

**Comment by vvvar** [comment]
Closing since in newer version installer was replaced with just plugin files. 
For now it is like that because turned out one shall have an expensive certificate to build and sign an .exe installers on Windows and I don't have one for now. Signing with cheap/free certificates unfortunately gives no guarantee that it will work, Windows can still block it. So for now please use manual installation.
