### ISSUE TITLE
Build fail with recent JUCE and manufacture code.

### ISSUE THREAD

**Issue by KottV** [vvvar/PeakEater#3]
With JUCE-6.1.2 when doing `Projucer --resave` you'll got the:

`Error when saving: The plugin manufacturer code must contain exactly four characters.`

It could be easy fixed by changing to `pluginManufacturerCode="T-AD"` for example.

**Comment by vvvar** [comment]
Fixed with upgrade to the new CMake build system. New build instructions are [here](https://github.com/vvvar/PeakEater#building-from-sources).
Sorry somehow lost this ticket and forgot to mention it although it shall be fixed.
