### ISSUE TITLE
Visualise clipping algorithm

### ISSUE THREAD

**Issue by vvvar** [vvvar/PeakEater#30]
Add visualisation for currently chosen clipping algorithm.
Draft idea: display waveform in the central panel after algorithm was switched, and fade it away.

**Comment by yupyup-cmyk** [comment]
I was going to make a request for this but glad to see you're already thinking about it!

**Comment by vvvar** [comment]
Available from [v.0.4.0](https://github.com/vvvar/PeakEater/releases/tag/v0.4.0).
