### ISSUE TITLE
Better Color

### ISSUE THREAD

**Issue by Daniele71** [vvvar/PeakEater#40]
Hi, light green and light grey are a bit hard to see. Maybe more saturated/darker tones would help. Thanks.

**Comment by vvvar** [comment]
Hey, thanks for the feedback, new design is coming, here is a glimpse.
<img width="686" alt="Screenshot 2022-12-16 at 23 32 05" src="https://user-images.githubusercontent.com/32337080/208199699-2b2de5eb-5af7-43e6-acaf-945d103a304b.png">

**Comment by Daniele71** [comment]
Oh it's great ! Keep it up, there aren't many alternatives in the open source world...

**Comment by vvvar** [comment]
Closing just because UI was reworked since opening and just to keep it clean :)
But if you have further suggestions - feel free to either re-open or create a new ticket.
