### ISSUE TITLE
Ошибка запуска на macOS Mojave в Bitwig 4.4

### ISSUE THREAD

**Issue by AlexeySovid** [vvvar/PeakEater#60]
/Library/Audio/Plug-Ins/CLAP/PeakEater.clap

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Could not load executable: Пакет поврежден или отсутствуют необходимые ресурсы.
-------------------------------------------------------------------

/Library/Audio/Plug-Ins/VST3/PeakEater.vst3

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Could not load executable: Пакет поврежден или отсутствуют необходимые ресурсы.
-------------------------------------------------------------------

/Users/Anonim/Documents/CLAP/PeakEater.clap

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Could not load executable: Пакет поврежден или отсутствуют необходимые ресурсы.
-------------------------------------------------------------------

/Volumes/PeakEater-0.4.0/PeakEater.vst3

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Could not load executable: Пакет поврежден или отсутствуют необходимые ресурсы.
-------------------------------------------------------------------

МакБук с процессором intel

**Comment by vvvar** [comment]
Спасибо за баг-репорт.
Проверил последний релиз на Bitwig Studio 4.4.8(macOS Monteray 12.6.3) - работает.
Попробуй, пожалуйста, последний релиз - https://github.com/vvvar/PeakEater/releases/tag/v0.6.0

Will dupe in English, just in case someone running the same issue.
Checked the latest release with Betwig Studio 4.4.8(macOS Monteray 12.6.3) - works.
Please check out latest release - https://github.com/vvvar/PeakEater/releases/tag/v0.6.0

**Comment by vvvar** [comment]
<img width="1137" alt="Screenshot 2023-03-19 at 18 36 13" src="https://user-images.githubusercontent.com/32337080/226196974-505c6c66-02aa-4b4a-b68d-7f23451b22e8.png">

**Comment by vvvar** [comment]
Checked one time with Bitwig 5.0. Both CLAP and VST3 seems works normal. No errors reported.
<img width="1322" alt="Screenshot 2023-07-05 at 20 35 01" src="https://github.com/vvvar/PeakEater/assets/32337080/e2e59b1f-c708-475c-bc9e-311c034248e2">
<img width="1322" alt="Screenshot 2023-07-05 at 20 34 59" src="https://github.com/vvvar/PeakEater/assets/32337080/9a5b7611-90d5-4e49-b60a-1cae18ed35bd">

Closing for now but if you'll run into same problem again - please open a new bug request. 
Also please use the latest version:
https://github.com/vvvar/PeakEater/releases/tag/v0.7.2
