### ISSUE TITLE
[Bug] AU fails plugin validation in Logic

### ISSUE THREAD

**Issue by 5T33Z0** [vvvar/PeakEater#70]
I Can't get the plugin to work in Logic Pro 1.7.4 nor N.I. Maschine.

OS: Big Sur 11.7.4

Below you find the log from Logic's Plugin Validation:

```
validating Audio Unit PeakEater by T-Audio:

    AU Validation Tool
    Version: 1.8.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aufx' - 'Tape' - 'Tado'
--------------------------------------------------
Manufacturer String: T-Audio
AudioUnit Name: PeakEater
Component Version: 0.5.1 (0x501)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF


validation result: couldn’t be opened
```

**Comment by vvvar** [comment]
There was some changes in AU build system in new version of PeakEater. Check it with the new version with LogicPro 10.7.8(PeakEater v0.7.2). Works fine:

<img width="785" alt="Screenshot 2023-07-05 at 20 55 47" src="https://github.com/vvvar/PeakEater/assets/32337080/e4b917e4-77d6-453d-a400-1cd2f3696efc">

Could you please check with this version of PeakEater?
https://github.com/vvvar/PeakEater/releases/tag/v0.7.2

**Comment by 5T33Z0** [comment]
Working fine now, thanks!
