### ISSUE TITLE
[Bug] 'Link input with output' doesn't remain green when selected

### ISSUE THREAD

**Issue by evilcream** [vvvar/PeakEater#82]
**Describe the bug**
If I enable 'link input with output', the text will turn green. But if I close and re-open the interface the text has returned to white but the link is still active

**To Reproduce**
1) Enable 'link input with output'
2) Close interface
3) Re-open it

**Expected behavior**
I expected the linked input/output graphic to remain green once selected

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin format VST3
 - Version [0.6.2]

**DAW:**
 - Name: [FL Studio]
 - Version [20.9.2]

**Additional context**

**Comment by vvvar** [comment]
Was able to reproduce, seems general issue, will have a look. Thanks!

**Comment by vvvar** [comment]
Fixed in [v0.8.1](https://github.com/vvvar/PeakEater/releases/tag/v0.8.1).
